version: '2.1'

services:
    db:
      image: postgres
      healthcheck:
        test: exit 0
      ports:  #will need to change these ports if multiple change external port to something unique ex 6005:5432
      - 6005:5432
      environment:
        - POSTGRES_DB=students_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
      volumes:    # will let you start up an initial database with an sql file in the area
          - ./studentDBinit.sql:/docker-entrypoint-initdb.d/studentDBinit.sql
          # can add persistance by adding to studentDBinit.sql upon db changes

    server:
      build: .    # . this will make the dockercompose build the server itself (in the local environment)
      command: npm run serverStart
      image: willjantscher/students_server:latest #make sure to include this!, references top-folder_service-name
      environment:
        - DATABASE_URL=postgres://admin:admin@db:5432
        - NODE_ENV=test
      depends_on:
        db:
          condition: service_healthy
      links:
        - db
      ports:
        - 6004:6004   #server should mount on port 6004, 6004 is internal port for the server

    app:
      build: 
        context: .
        dockerfile: Dockerfile
      volumes:
        - '.:/app'
        - '/app/node_modules'
      # command: npm start
      image: willjantscher/students_app:latest
      depends_on: 
        - server
      links:
        - server
      ports:
        - 6001:6002
      environment:
        - CHOKIDAR_USEPOLLING=true


    